[package]
name = "scaleway-registry-prune"
version = "0.0.0"
authors = ["Mikkel Kroman <mk@maero.dk>"]
edition = "2018"

[dependencies]
clap = "2.33"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
humantime = "2.0"
